using Cereal_API.Models;
using Microsoft.EntityFrameworkCore;

namespace Cereal_API.Repositories;

public class CerealRepository : ICerealRepository
{
    private readonly CerealDbContext _context;

    public CerealRepository(CerealDbContext context)
    {
        _context = context;
    }

    public async Task<Cereal> GetCerealById(Guid id)
    {
        var cereal = await _context.Cereals.FindAsync(id);

        if (cereal == null)
        {
            throw new Exception($"Cereal with ID {id} not found.");
        }

        return cereal;
    }

    public async Task<Cereal> GetCerealByName(string name)
    {
        throw new NotImplementedException();
    }

    public async Task<IEnumerable<Cereal>> GetAllCereals()
    {
        var cereals = await _context.Cereals.ToListAsync();

        if (cereals == null || cereals.Count == 0)
        {
            throw new Exception("No cereals found.");
        }

        return cereals;
    }

    public async Task<IEnumerable<Cereal>> GetSortedCereals(string operatorAndValue, string category)
    {
        throw new NotImplementedException();
    }

    public async Task<Cereal> CreateCereal(Cereal cereal)
    {
        // should we check if the cereal already exists by name? Perhaps a future thing

        Cereal newCereal = cereal with { Id = Guid.NewGuid() };

        _context.Cereals.Add(newCereal);
        await _context.SaveChangesAsync();

        return newCereal;
    }

    public async Task<Cereal> UpdateCereal(Guid id, Cereal cereal)
    {
        throw new NotImplementedException();

        // generated by template
        //if (id != cereal.Id)
        //{
        //    return BadRequest();
        //}

        //_context.Entry(cereal).State = EntityState.Modified;

        //try
        //{
        //    await _context.SaveChangesAsync();
        //}
        //catch (DbUpdateConcurrencyException)
        //{
        //    if (!CerealExists(id))
        //    {
        //        return NotFound();
        //    }
        //    else
        //    {
        //        throw;
        //    }
        //}

        //return NoContent();
    }

    public async Task<bool> DeleteCereal(Guid id)
    {
        throw new NotImplementedException();
    }

    public bool CerealExists(Guid id)
    {
        return _context.Cereals.Any(e => e.Id == id);
    }
}
