using Microsoft.AspNetCore.Mvc;
using Cereal_API.Models;
using Cereal_API.Repositories;
using Cereal_API.Models.Types;

namespace Cereal_API.Controllers;

[Route("api/[controller]")]
[ApiController]
public class CerealController : Controller
{
    private readonly ICerealRepository _cerealRepository;

    /// <summary>
    /// Initializes a new instance of the CerealController class using the specified cereal repository.
    /// </summary>
    /// <param name="cerealRepository">The repository used to access and manage cereal data. Cannot be null.</param>
    public CerealController(ICerealRepository cerealRepository)
    {
        _cerealRepository = cerealRepository;
    }

    // GET: api/Cereal
    [HttpGet]
    public async Task<ActionResult<IEnumerable<Cereal>>> GetCereals()
    {
        try
        {
            var cereals = await _cerealRepository.GetAllCereals();
            return View(cereals);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    // GET: api/Cereal/?????
    [HttpGet]
    public async Task<ActionResult<IEnumerable<Cereal>>> GetCereals(string category, OperatorType operation, string value)
    {
        if (category == null || value == null)
        {
            return BadRequest("All fields need a value.");
        }

        try
        {
            var cereals = await _cerealRepository.GetFilteredCereals(category, operation, value);
            return View(cereals);
        } 
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    // GET: api/Cereal/5
    [HttpGet("{id}")]
    public async Task<ActionResult<Cereal>> GetCereal(Guid id)
    {
        try
        {
            var cereal = await _cerealRepository.GetCerealById(id);
            return cereal;
        }
        catch (Exception ex)
        {
            return NotFound(ex.Message);
        }
    }

    // POST: api/Cereal
    // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
    [HttpPost]
    public async Task<ActionResult<Cereal>> PostCereal(Cereal cereal)
    {
        if (cereal.Id != Guid.Empty)
        {
            return BadRequest("New cereal must not have an ID. The ID will be generated by the server.");
        }

        try
        {
            var createdCereal = await _cerealRepository.CreateCereal(cereal);
            return CreatedAtAction("GetCereal", new { id = createdCereal.Id }, createdCereal);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    // POST: api/Cereal/5
    // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
    [HttpPost("{id}")]
    public async Task<IActionResult> PostCereal(Guid id, Cereal cereal)
    {
        if (id != cereal.Id)
        {
            return BadRequest();
        }

        if (!_cerealRepository.CerealExists(id))
        {
            return BadRequest("User cannot choose ID for new objects");
        }

        try
        {
            await _cerealRepository.UpdateCereal(id, cereal);
            return NoContent();
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    // DELETE: api/Cereal/5
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteCereal(Guid id)
    {
        if (!_cerealRepository.CerealExists(id))
        {
            return NotFound("Cereal not found.");
        }

        try
        {
            await _cerealRepository.DeleteCereal(id);
            return NoContent();
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }
}
